/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface SourcePosition {
  line: number
  column: number
  offset: number
}
export interface SourceSpan {
  start: SourcePosition
  end: SourcePosition
}
export const enum TK {
  ContextSwitch = 0,
  Indent = 1,
  Dedent = 2,
  Newline = 3,
  DimensionData = 4,
  DimensionStyle = 5,
  DimensionBehavior = 6,
  ControlIf = 7,
  ControlElseIf = 8,
  ControlElse = 9,
  ControlEach = 10,
  Slot = 11,
  Tag = 12,
  Component = 13,
  Text = 14,
  Comment = 15,
  RawLine = 16,
  Eof = 17
}
export interface Token {
  type: TK
  value: string
  line: number
  col: number
  indent: number
  span: SourceSpan
}
export interface LexError {
  message: string
  line: number
  span?: SourceSpan
}
export interface LexerResult {
  tokens: Array<Token>
  errors: Array<LexError>
}
export interface TokenEstimates {
  source: number
  outline: number
  edit: number
}
export interface IndexManifestEntry {
  sourcePath: string
  sourceHash: string
  cacheFile: string
  language: string
  tokenEstimates: TokenEstimates
  diagnostics: number
  generatedAt: string
}
export interface IndexManifest {
  version: number
  root: string
  generatedAt: string
  files: Array<IndexManifestEntry>
}
export interface IndexerResult {
  manifest: IndexManifest
  indexed: number
  reused: number
  removed: number
}
export declare function hashText(text: string): string
export declare function indexWorkspace(root: string, cacheDir?: string | undefined | null, inputs?: Array<string> | undefined | null): IndexerResult
export declare function napiTokenize(src: string): LexerResult
export declare function napiParse(src: string): any
